In [86]:
import pandas as pd

combine2021 = pd.read_csv("2021Combine.csv")
#combine2021
stats2021 = pd.read_csv("2021Stats.csv")
#stats2021

combine2022 = pd.read_csv("2022Combine.csv")
#combine2022
stats2022 = pd.read_csv("2022Stats.csv")
#stats2022

combine2023 = pd.read_csv("2023Combine.csv")
#combine2023
stats2023 = pd.read_csv("2023Stats.csv")
#stats2023



# All Stats
stats2021 = stats2021.iloc[1:]
stats2022 = stats2022.iloc[1:]
stats2023 = stats2023.iloc[1:]
statsAll = pd.concat([stats2021, stats2022, stats2023], ignore_index = True)

removeCols = ["Unnamed: 6", "Unnamed: 27", "Unnamed: 28", "#NAME?"]
statsAll = statsAll.drop(columns = removeCols)

cols = ["Rnd", "Pick", "Tm", "Name", "Pos", "Age", "APs", "PBs", "YrsStart", "PlAV", "TmAV", "GP", "PasCmp", "PasAtt", "PasYds", "PasTDs", "PasInts", "RusAtt", "RusYds", "RusTDs", "RecRec", "RecYds", "RecTDs", "DefTkl", "DefInt", "DefSk"]
statsAll.columns = cols
# ---


# All Combine
combineAll = pd.concat([combine2021, combine2022, combine2023], ignore_index = True)

removeCols = ["School", "College", "Drafted (tm/rnd/yr)", "Player-additional"]
combineAll = combineAll.drop(columns = removeCols)

cols = ["Name", "Pos", "Ht", "Wt", "40Yd", "Vert", "Bnch", "BdJmp", "3Cn", "Shut"]
combineAll.columns = cols

# Excel Automatically Changes 6-2 to 2-June and Ht Was Originally Formatted in This Way
monthToHeight = {
    'Jan': '1', 'Feb': '2', 'Mar': '3', 'Apr': '4', 
    'May': '5', 'Jun': '6', 'Jul': '7', 'Aug': '8', 
    'Sep': '9', 'Oct': '10', 'Nov': '11', 'Dec': '12'
}

temp = combineAll['Ht'].str.split('-', expand = True)
temp[1] = temp[1].map(monthToHeight)

combineAll['Ht'] = temp[1] + "-" + temp[0]
# ---



# All Data
allData = pd.merge(
    statsAll, 
    combineAll.drop(columns = ["Pos"], errors = "ignore"), 
    on = "Name", 
    how = "left"
)

#allData
# ---



# QB Data
qbAll = allData[allData["Pos"] == "QB"].copy()
removeCols = ["RecRec", "RecYds", "RecTDs", "DefTkl", "DefInt", "DefSk"]
qbAll = qbAll.drop(columns = removeCols)

qbAll
# ---



# WR Data
wrAll = allData[allData["Pos"] == "WR"].copy()
removeCols = ["PasCmp", "PasAtt", "PasYds", "PasTDs", "DefTkl", "DefInt", "DefSk"]
wrAll = wrAll.drop(columns = removeCols)

wrAll
# ---



# RB Data
rbAll = allData[allData["Pos"] == "RB"].copy()
removeCols = ["PasCmp", "PasAtt", "PasYds", "PasTDs", "DefTkl", "DefInt", "DefSk"]
rbAll = rbAll.drop(columns = removeCols)

rbAll
# ---



# Defense Data
defensivePositions = ["LB", "DB", "S", "OLB", "DL", "DE", "DT"]
defenseAll = allData[allData["Pos"].isin(defensivePositions)].copy()
removeCols = ["PasCmp", "PasAtt", "PasYds", "PasTDs", "RusAtt", "RusYds", "RusTDs", "RecRec", "RecYds", "RecTDs"]
defenseAll = defenseAll.drop(columns = removeCols)

defenseAll["PlAV"] = pd.to_numeric(defenseAll["PlAV"], errors = "coerce")

defenseAll
# ---

allData

    Rnd Pick   Tm                      Name  Pos  Age APs PBs YrsStart PlAV TmAV   GP PasCmp PasAtt PasYds PasTDs PasInts RusAtt RusYds RusTDs RecRec RecYds RecTDs DefTkl DefInt DefSk    Ht     Wt  40Yd  Vert  Bnch  BdJmp   3Cn  Shut
0     1    1  JAX           Trevor Lawrence   QB   21   0   1        5   52   52   77   1629   2594  17822     98      58    313   1442     23      0     -5      0      4    NaN   NaN   6-5  213.0   NaN   NaN   NaN    NaN   NaN   NaN
1     1    2  NYJ               Zach Wilson   QB   22   0   0        3   13   13   38    572   1004   6325     23      25     96    499      5      1      2      1      1    NaN   NaN   6-2  214.0   NaN   NaN   NaN    NaN   NaN   NaN
2     1    3  SFO                Trey Lance   QB   21   0   0        0    6    4   16    108    200   1289      5       5     82    361      1      0      0      0      1    NaN   NaN   6-3  224.0   NaN   NaN   NaN    NaN   NaN   NaN
3     1    4  ATL                Kyle Pitts   TE   20   0   1        5   28   28   78      0      0      0      0       0      1     -4      0    284   3579     15      3    NaN   NaN   6-5  245.0  4.44  33.5  22.0  129.0  7.12  4.30
4     1    5  CIN             Ja'Marr Chase   WR   21   2   5        5   58   58   78      1      1     -7      0       0     21     69      0    520   6837     54      6    NaN   NaN   NaN  201.0  4.34  41.0   NaN  132.0  6.96  3.99
5     1    6  MIA             Jaylen Waddle   WR   22   0   0        5   41   41   78      1      1      8      0       0     14     81      1    373   5039     26      4    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
6     1    7  DET              Penei Sewell   OL   20   3   4        5   64   64   83      0      0      0      0       0      0      0      0      1      9      0    NaN    NaN   NaN   6-4  331.0  5.13  28.0  30.0  109.0  7.76  4.68
7     1    8  CAR               Jaycee Horn   DB   21   0   2        3   22   22   53      0      0      0      0       0      0      0      0      0      0      0    135     10     2   NaN  205.0  4.39  41.5  19.0  133.0   NaN   NaN
8     1    9  DEN        Patrick Surtain II   DB   21   2   4        5   51   51   80      0      0      0      0       0      0      0      0      0      0      0    221     12   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
9     1   10  PHI             DeVonta Smith   WR   22   0   0        5   47   47   80      0      0      0      0       0      1      1      0    385   5019     31      1    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
10    1   11  CHI             Justin Fields   QB   22   0   0        4   44   34   59    812   1323   9039     52      32    489   2892     23      0      0      0    NaN    NaN   NaN   6-2  227.0  4.45   NaN   NaN    NaN   NaN   NaN
11    1   12  DAL             Micah Parsons   LB   22   3   5        4   67   56   77      0      0      0      0       0      0      0      0      0      0      0    191    NaN    65   6-3  246.0  4.39  34.0  19.0  126.0  6.89  4.40
12    1   13  LAC            Rashawn Slater   OL   22   0   2        3   32   32   51      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   6-4  304.0  4.91  33.0  33.0  112.0  7.48  4.45
13    1   14  NYJ        Alijah Vera-Tucker   OL   22   0   0        2   14   14   43      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   6-4  308.0  5.05  32.0  36.0  106.0  7.67  4.70
14    1   15  NWE                 Mac Jones   QB   23   0   1        3   34   24   63   1236   1859  12741     67      50    181    479      2      0      0      0      1    NaN   NaN   6-2  217.0  4.72  32.0   NaN  116.0  7.04  4.39
15    1   16  ARI             Zaven Collins   LB   22   0   0        4   24   24   84      0      0      0      0       0      0      0      0      0      0      0    162      2    12   6-4  259.0  4.67  35.0  19.0  122.0   NaN  4.36
16    1   17  LVR          Alex Leatherwood   OL   22   0   0        1    8    8   21      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   6-5  312.0  4.96  34.5   NaN  118.0   NaN   NaN
17    1   18  MIA           Jaelan Phillips   DL   22   0   0        2   23   19   63      0      0      0      0       0      0      0      0      0      0      0    119      1    28   6-5  260.0  4.56  36.0  21.0  125.0   NaN   NaN
18    1   19  WAS               Jamin Davis   LB   22   0   0        2   16   16   56      0      0      0      0       0      0      0      0      0      0      0    179      1     8   6-3  234.0  4.47  42.0   NaN  132.0   NaN   NaN
19    1   20  NYG            Kadarius Toney   WR   22   0   0        0    7    3   35      1      4     19      0       0     23    115      1     82    760      3      1    NaN   NaN  5-11  193.0  4.39  39.5   9.0  136.0  6.88  4.25
20    1   21  IND                Kwity Paye   DL   22   0   0        5   32   32   75      0      0      0      0       0      0      0      0      0      0      0    123    NaN  30.5   6-2  261.0  4.52  35.3  36.0  118.0   NaN   NaN
21    1   22  TEN              Caleb Farley   DB   22   0   0        0    2    1   21      0      0      0      0       0      0      0      0      0      0      0     24    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
22    1   23  MIN        Christian Darrisaw   OL   22   0   0        4   26   26   58      0      0      0      0       0      0      0      0      0      0      0      1    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
23    1   24  PIT              Najee Harris   RB   23   0   1        4   30   29   71      1      1      4      0       0   1112   4373     28    183   1174      6      4    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
24    1   25  JAX            Travis Etienne   RB   22   0   0        4   33   33   66      0      0      0      0       0    897   3798     25    168   1338      7    NaN    NaN   NaN  5-10  215.0  4.45  33.5  18.0  128.0   NaN   NaN
25    1   26  CLE           Greg Newsome II   DB   21   0   0        4   19   16   71      0      0      0      0       0      0      0      0      0      0      0    163      4     1   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
26    1   27  BAL            Rashod Bateman   WR   21   0   0        3   20   20   64      0      0      0      0       0      1     18      0    157   2147     15    NaN    NaN   NaN   NaN  190.0  4.39  36.0   NaN  123.0   NaN   NaN
27    1   28  NOR             Payton Turner   DE   22   0   0        0    3    3   31      0      0      0      0       0      0      0      0      0      0      0     30    NaN     5   6-5  268.0   NaN  35.5  23.0    NaN  6.98  4.33
28    1   29  GNB               Eric Stokes   DB   22   0   0        4   14    9   61      0      0      0      0       0      0      0      0      0      0      0    133      1   NaN   NaN  194.0  4.31  38.5  14.0  128.0  6.96  4.36
29    1   30  BUF          Gregory Rousseau   DL   21   0   0        5   38   38   78      0      0      0      0       0      0      0      0      0      0      0    159      1    32   6-6  266.0  4.68  30.0  21.0  115.0   NaN   NaN
30    1   31  BAL                Odafe Oweh   DE   22   0   0        1   16   15   79      0      0      0      0       0      0      0      0      0      0      0    118    NaN  30.5   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
31    1   32  TAM        Joe Tryon-Shoyinka  OLB   22   0   0        3   23   22   82      0      0      0      0       0      0      0      0      0      0      0     97    NaN    15   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
32    2   33  JAX            Tyson Campbell   DB   21   0   0        5   25   20   72      0      0      0      0       0      0      0      0      0      0      0    241      7   NaN   6-1  193.0  4.40  34.5  12.0  124.0  7.15  4.45
33    2   34  NYJ              Elijah Moore   WR   21   0   0        3   15    7   70      0      0      0      0       0     26     95      2    209   2274      9      4    NaN   NaN   NaN    NaN  4.35  36.0  17.0  121.0  6.63  4.07
34    2   35  DEN          Javonte Williams   RB   21   0   0        3   28   19   70      0      0      0      0       0    858   3595     22    193   1103      7      1    NaN   NaN   5-9  212.0  4.55  36.0  22.0  123.0  6.97  4.09
35    2   36  MIA             Jevon Holland    S   21   0   0        5   25   21   74      0      0      0      0       0      0      0      0      0      0      0    257      6     5   NaN  207.0  4.48  35.5  19.0  126.0   NaN  4.14
36    2   37  PHI          Landon Dickerson   OL   22   0   3        5   36   36   78      0      0      0      0       0      0      0      0      0      0      0      1    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
37    2   38  NWE         Christian Barmore   DL   22   0   0        1   17   17   65      0      0      0      0       0      0      0      0      0      0      0     95    NaN  15.5   6-4  310.0  4.93   NaN   NaN    NaN   NaN   NaN
38    2   39  CHI             Teven Jenkins   OL   23   0   0        3   17   15   62      0      0      0      0       0      0      0      0      0      0      0      2    NaN   NaN   6-5  317.0  5.01  32.5  36.0  106.0  7.72  4.66
39    2   40  ATL              Richie Grant   DB   23   0   0        2   13   13   68      0      0      0      0       0      0      0      0      0      0      0    178      3     3  5-11  197.0  4.49  34.5  12.0  129.0  6.78  4.27
40    2   41  DET           Levi Onwuzurike   DL   23   0   0        1    7    7   42      0      0      0      0       0      0      0      0      0      0      0     35    NaN   3.5   6-2  290.0  4.89  30.0  29.0  109.0   NaN   NaN
41    2   42  MIA           Liam Eichenberg   OL   23   0   0        4   23   23   60      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   6-6  306.0   NaN  26.5  33.0  105.0  7.53  4.58
42    2   43  LVR           Tre'von Moehrig    S   22   0   0        5   25   20   82      0      0      0      0       0      0      0      0      0      0      0    267      7     6   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
43    2   44  DAL             Kelvin Joseph   DB   21   0   0        0    2    2   33      0      0      0      0       0      0      0      0      0      0      0     34    NaN   NaN  5-11  197.0  4.34  35.0   NaN  128.0  7.21  4.22
44    2   45  JAX             Walker Little    T   22   0   0        2   18   18   70      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   6-7  313.0  5.30  29.5  24.0  111.0  7.44  4.59
45    2   46  CIN            Jackson Carman    T   21   0   0        0    5    4   30      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   6-4  317.0   NaN   NaN   NaN    NaN   NaN   NaN
46    2   47  LAC         Asante Samuel Jr.   DB   21   0   0        3   15   14   56      0      0      0      0       0      0      0      0      0      0      0    154      7   NaN  5-10  180.0  4.45  35.0  12.0  124.0  6.95  4.13
47    2   48  SFO               Aaron Banks   OL   24   0   0        4   26   20   68      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   6-5  325.0  5.32  31.0  24.0  100.0  7.69  4.89
48    2   49  ARI             Rondale Moore   WR   21   0   0        0   12   12   39      0      0      0      0       0     52    249      1    135   1201      3      1    NaN   NaN   5-7  180.0  4.28  42.5   NaN    NaN  6.65  4.06
49    2   50  NYG             Azeez Ojulari  OLB   21   0   0        1   17   16   49      0      0      0      0       0      0      0      0      0      0      0     61    NaN    22   6-2  249.0  4.63  30.0  26.0  127.0  7.27  4.34
50    2   51  WAS              Samuel Cosmi   OL   22   0   0        3   26   26   66      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   6-5  314.0  4.87  30.0  36.0  117.0  7.35  4.39
51    2   52  CLE   Jeremiah Owusu-Koramoah   LB   21   0   1        3   22   22   49      0      0      0      0       0      0      0      0      0      0      0    205      3     8   6-1  221.0   NaN  36.5   NaN  124.0  6.80  4.15
52    2   53  TEN             Dillon Radunz    T   23   0   0        3   14   11   69      0      0      0      0       0      0      0      0      0      0      0      1    NaN   NaN   6-5  301.0  5.16  32.0  24.0  112.0  7.27  4.57
53    2   54  IND            Dayo Odeyingbo   DL   21   0   0        1   15   12   69      0      0      0      0       0      0      0      0      0      0      0     67    NaN  17.5   6-5  276.0   NaN   NaN   NaN    NaN   NaN   NaN
54    2   55  PIT            Pat Freiermuth   TE   22   0   0        2   22   22   78      0      0      0      0       0      0      0      0    261   2676     22      2    NaN   NaN   6-5  251.0   NaN   NaN  26.0    NaN   NaN   NaN
55    2   56  SEA          D'Wayne Eskridge   WR   24   0   0        0    3    2   43      0      0      0      0       0      8     74      0     24    228      1      1    NaN   NaN   5-8  190.0  4.38  35.0   NaN  124.0  6.93  4.22
56    2   57  LAR               Tutu Atwell   WR   21   0   0        1   14   14   64      0      1      0      0       0     16     72      1    105   1535      5    NaN    NaN   NaN   5-8  155.0  4.42  33.0   NaN  117.0  6.89  4.14
57    2   58  KAN               Nick Bolton   LB   21   0   0        4   30   30   74      0      0      0      0       0      0      0      0      0      0      0    362      5     6  5-11  237.0  4.60  32.0  24.0    NaN  7.40  4.50
58    2   59  CAR      Terrace Marshall Jr.   WR   21   0   0        1    6    6   43      0      0      0      0       0      0      0      0     67    808      1      1    NaN   NaN   6-2  205.0  4.40  39.0  19.0  125.0   NaN   NaN
59    2   60  NOR               Pete Werner   LB   22   0   0        4   30   30   73      0      0      0      0       0      0      0      0      0      0      0    256      1   2.5   6-2  238.0  4.58  39.5  20.0  122.0  6.95  4.38
60    2   61  BUF             Boogie Basham   DL   23   0   0        0    4    3   43      0      0      0      0       0      0      0      0      0      0      0     27      1   4.5   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
61    2   62  GNB                Josh Myers    C   23   0   0        4   32   27   73      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   6-5  310.0   NaN   NaN  29.0    NaN   NaN   NaN
62    2   63  KAN            Creed Humphrey   OL   22   2   4        5   51   51   85      0      0      0      0       0      0      0      0      0      0      0      1    NaN   NaN   6-4  302.0  5.11  33.0  29.0  112.0  7.50  4.49
63    2   64  TAM                Kyle Trask   QB   23   0   0        0    0    0    7      4     11     28      0       0      6     -5      0      0      0      0    NaN    NaN   NaN   6-5  236.0  5.10  31.5   NaN  113.0  7.08  4.60
64    3   65  JAX               Andre Cisco   DB   21   0   0        3   20   18   71      0      0      0      0       0      0      0      0      0      0      0    180      8   1.5   NaN    NaN   NaN   NaN  17.0    NaN   NaN   NaN
65    3   66  MIN               Kellen Mond   QB   22   0   0        0    0    0    1      2      3      5      0       0      0      0      0      0      0      0    NaN    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
66    3   67  HOU               Davis Mills   QB   22   0   0        2   17   17   44    684   1107   7082     40      26     68    232      3      0      0      0      2    NaN   NaN   6-3  217.0  4.82  32.0   NaN  110.0  6.95  4.40
67    3   68  ATL            Jalen Mayfield   OL   21   0   0        1    7    7   19      0      0      0      0       0      0      0      0      0      0      0    NaN    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
68    3   69  CIN              Joseph Ossai   LB   21   0   0        1   10   10   61      0      0      0      0       0      0      0      0      0      0      0     59    NaN  14.5   6-3  256.0  4.63  41.5  19.0  131.0   NaN   NaN
69    3   70  CAR         Brady Christensen   OL   24   0   0        1   14   14   59      0      0      0      0       0      0      0      0      0      0      0      1    NaN   NaN   NaN    NaN   NaN  34.0  30.0  124.0   NaN   NaN
70    3   71  NYG            Aaron Robinson   DB   22   0   0        0    2    2   11      0      0      0      0       0      0      0      0      0      0      0     21    NaN   NaN  5-11  186.0  4.39  37.0  15.0  123.0  6.89  4.29
71    3   72  DET              Alim McNeill   DT   21   0   0        4   23   23   71      0      0      0      0       0      0      0      0      0      0      0     71    NaN  12.5   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
72    3   73  PHI           Milton Williams   DL   22   0   0        2   17   11   79      0      0      0      0       0      0      0      0      0      0      0     81    NaN    15   6-3  284.0  4.67  38.5  34.0  121.0  6.96  4.33
73    3   74  WAS         Benjamin St-Juste   DB   23   0   0        3   14   12   70      0      0      0      0       0      0      0      0      0      0      0    184      2     3   6-3  202.0  4.51  34.5  11.0  119.0  6.63  3.96
74    3   75  DAL            Osa Odighizuwa   DL   23   0   0        5   31   31   84      0      0      0      0       0      0      0      0      0      0      0    115    NaN    17   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
75    3   76  NOR             Paulson Adebo   CB   22   0   0        5   22   19   64      0      0      0      0       0      0      0      0      0      0      0    265     11   NaN   6-1  198.0  4.45  36.5  18.0  121.0  6.69  4.13
76    3   77  LAC               Josh Palmer   WR   21   0   0        1   21   19   70      0      0      0      0       0      3     16      0    204   2590     10      2    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
77    3   78  MIN             Chazz Surratt   LB   24   0   0        0    6    1   52      0      0      0      0       0      0      0      0      0      0      0     29    NaN   NaN   6-2  229.0  4.58  31.0  25.0    NaN  7.02  4.16
78    3   79  LVR            Malcolm Koonce   DE   23   0   0        1    9    9   56      0      0      0      0       0      0      0      0      0      0      0     54    NaN  14.5   6-2  249.0   NaN   NaN   NaN    NaN   NaN   NaN
79    3   80  LVR             Divine Deablo   DB   23   0   0        3   25   19   67      0      0      0      0       0      0      0      0      1     34      0    204    NaN     3   6-3  226.0  4.42  34.0  19.0  126.0  7.12  4.40
80    3   81  MIA               Hunter Long   TE   23   0   0        0    2    0   46      0      0      0      0       0      0      0      0     20    153      2      3    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
81    3   82  WAS               Dyami Brown   WR   21   0   0        0    7    6   77      1      2      4      0       0     12     67      0     79   1011      5      4    NaN   NaN   NaN  189.0  4.46  35.0  18.0  128.0  6.87  4.35
82    3   83  CAR             Tommy Tremble   TE   21   0   0        2    7    7   78      0      0      0      0       0      3     11      1    112   1031     11      8    NaN   NaN   6-3  241.0  4.60  36.5  20.0  122.0   NaN   NaN
83    3   84  DAL          Chauncey Golston   DL   23   0   0        0   12   12   74      0      0      0      0       0      0      0      0      0      0      0     81      1    10   6-4  269.0  4.79  36.0   NaN  119.0  7.52  4.65

In [85]:
defenseAll

    Rnd Pick   Tm                     Name  Pos  Age APs PBs YrsStart  PlAV TmAV   GP PasInts DefTkl DefInt DefSk    Ht     Wt  40Yd  Vert  Bnch  BdJmp   3Cn  Shut
7     1    8  CAR              Jaycee Horn   DB   21   0   2        3  22.0   22   53       0    135     10     2   NaN  205.0  4.39  41.5  19.0  133.0   NaN   NaN
8     1    9  DEN       Patrick Surtain II   DB   21   2   4        5  51.0   51   80       0    221     12   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
11    1   12  DAL            Micah Parsons   LB   22   3   5        4  67.0   56   77       0    191    NaN    65   6-3  246.0  4.39  34.0  19.0  126.0  6.89  4.40
15    1   16  ARI            Zaven Collins   LB   22   0   0        4  24.0   24   84       0    162      2    12   6-4  259.0  4.67  35.0  19.0  122.0   NaN  4.36
17    1   18  MIA          Jaelan Phillips   DL   22   0   0        2  23.0   19   63       0    119      1    28   6-5  260.0  4.56  36.0  21.0  125.0   NaN   NaN
18    1   19  WAS              Jamin Davis   LB   22   0   0        2  16.0   16   56       0    179      1     8   6-3  234.0  4.47  42.0   NaN  132.0   NaN   NaN
20    1   21  IND               Kwity Paye   DL   22   0   0        5  32.0   32   75       0    123    NaN  30.5   6-2  261.0  4.52  35.3  36.0  118.0   NaN   NaN
21    1   22  TEN             Caleb Farley   DB   22   0   0        0   2.0    1   21       0     24    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
25    1   26  CLE          Greg Newsome II   DB   21   0   0        4  19.0   16   71       0    163      4     1   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
27    1   28  NOR            Payton Turner   DE   22   0   0        0   3.0    3   31       0     30    NaN     5   6-5  268.0   NaN  35.5  23.0    NaN  6.98  4.33
28    1   29  GNB              Eric Stokes   DB   22   0   0        4  14.0    9   61       0    133      1   NaN   NaN  194.0  4.31  38.5  14.0  128.0  6.96  4.36
29    1   30  BUF         Gregory Rousseau   DL   21   0   0        5  38.0   38   78       0    159      1    32   6-6  266.0  4.68  30.0  21.0  115.0   NaN   NaN
30    1   31  BAL               Odafe Oweh   DE   22   0   0        1  16.0   15   79       0    118    NaN  30.5   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
31    1   32  TAM       Joe Tryon-Shoyinka  OLB   22   0   0        3  23.0   22   82       0     97    NaN    15   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
32    2   33  JAX           Tyson Campbell   DB   21   0   0        5  25.0   20   72       0    241      7   NaN   6-1  193.0  4.40  34.5  12.0  124.0  7.15  4.45
35    2   36  MIA            Jevon Holland    S   21   0   0        5  25.0   21   74       0    257      6     5   NaN  207.0  4.48  35.5  19.0  126.0   NaN  4.14
37    2   38  NWE        Christian Barmore   DL   22   0   0        1  17.0   17   65       0     95    NaN  15.5   6-4  310.0  4.93   NaN   NaN    NaN   NaN   NaN
39    2   40  ATL             Richie Grant   DB   23   0   0        2  13.0   13   68       0    178      3     3  5-11  197.0  4.49  34.5  12.0  129.0  6.78  4.27
40    2   41  DET          Levi Onwuzurike   DL   23   0   0        1   7.0    7   42       0     35    NaN   3.5   6-2  290.0  4.89  30.0  29.0  109.0   NaN   NaN
42    2   43  LVR          Tre'von Moehrig    S   22   0   0        5  25.0   20   82       0    267      7     6   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
43    2   44  DAL            Kelvin Joseph   DB   21   0   0        0   2.0    2   33       0     34    NaN   NaN  5-11  197.0  4.34  35.0   NaN  128.0  7.21  4.22
46    2   47  LAC        Asante Samuel Jr.   DB   21   0   0        3  15.0   14   56       0    154      7   NaN  5-10  180.0  4.45  35.0  12.0  124.0  6.95  4.13
49    2   50  NYG            Azeez Ojulari  OLB   21   0   0        1  17.0   16   49       0     61    NaN    22   6-2  249.0  4.63  30.0  26.0  127.0  7.27  4.34
51    2   52  CLE  Jeremiah Owusu-Koramoah   LB   21   0   1        3  22.0   22   49       0    205      3     8   6-1  221.0   NaN  36.5   NaN  124.0  6.80  4.15
53    2   54  IND           Dayo Odeyingbo   DL   21   0   0        1  15.0   12   69       0     67    NaN  17.5   6-5  276.0   NaN   NaN   NaN    NaN   NaN   NaN
57    2   58  KAN              Nick Bolton   LB   21   0   0        4  30.0   30   74       0    362      5     6  5-11  237.0  4.60  32.0  24.0    NaN  7.40  4.50
59    2   60  NOR              Pete Werner   LB   22   0   0        4  30.0   30   73       0    256      1   2.5   6-2  238.0  4.58  39.5  20.0  122.0  6.95  4.38
60    2   61  BUF            Boogie Basham   DL   23   0   0        0   4.0    3   43       0     27      1   4.5   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
64    3   65  JAX              Andre Cisco   DB   21   0   0        3  20.0   18   71       0    180      8   1.5   NaN    NaN   NaN   NaN  17.0    NaN   NaN   NaN
68    3   69  CIN             Joseph Ossai   LB   21   0   0        1  10.0   10   61       0     59    NaN  14.5   6-3  256.0  4.63  41.5  19.0  131.0   NaN   NaN
70    3   71  NYG           Aaron Robinson   DB   22   0   0        0   2.0    2   11       0     21    NaN   NaN  5-11  186.0  4.39  37.0  15.0  123.0  6.89  4.29
71    3   72  DET             Alim McNeill   DT   21   0   0        4  23.0   23   71       0     71    NaN  12.5   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
72    3   73  PHI          Milton Williams   DL   22   0   0        2  17.0   11   79       0     81    NaN    15   6-3  284.0  4.67  38.5  34.0  121.0  6.96  4.33
73    3   74  WAS        Benjamin St-Juste   DB   23   0   0        3  14.0   12   70       0    184      2     3   6-3  202.0  4.51  34.5  11.0  119.0  6.63  3.96
74    3   75  DAL           Osa Odighizuwa   DL   23   0   0        5  31.0   31   84       0    115    NaN    17   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
77    3   78  MIN            Chazz Surratt   LB   24   0   0        0   6.0    1   52       0     29    NaN   NaN   6-2  229.0  4.58  31.0  25.0    NaN  7.02  4.16
78    3   79  LVR           Malcolm Koonce   DE   23   0   0        1   9.0    9   56       0     54    NaN  14.5   6-2  249.0   NaN   NaN   NaN    NaN   NaN   NaN
79    3   80  LVR            Divine Deablo   DB   23   0   0        3  25.0   19   67       0    204    NaN     3   6-3  226.0  4.42  34.0  19.0  126.0  7.12  4.40
83    3   84  DAL         Chauncey Golston   DL   23   0   0        0  12.0   12   74       0     81      1    10   6-4  269.0  4.79  36.0   NaN  119.0  7.52  4.65
89    3   90  MIN         Patrick Jones II   DL   22   0   0        0   8.0    7   61       0     67    NaN    13   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
91    3   92  TEN               Monty Rice   LB   22   0   0        0   7.0    6   39       0     70    NaN   NaN   NaN  233.0  4.58  32.0   NaN  121.0  7.34  4.33
95    3   96  NWE           Ronnie Perkins   DE   21   0   0        0   0.0  NaN    7       0      9    NaN   NaN   6-2  253.0  4.71  32.0  25.0  115.0   NaN  4.69
98    3   99  DAL           Nahshon Wright   DB   22   0   1        1  11.0    2   50       0     81      6   NaN   6-4  183.0  4.46  31.0   6.0  126.0  7.24  4.57
99    3  100  TEN            Elijah Molden   DB   22   0   0        2  16.0    6   60       0    165      6   NaN   5-9  192.0  4.62  36.5  13.0  125.0   NaN   NaN
100   3  101  DET         Ifeatu Melifonwu   DB   22   0   0        0   8.0    6   53       0     84      3   5.5   6-2  205.0  4.48  41.5  16.0  134.0  7.01  4.34
101   3  102  SFO             Ambry Thomas   DB   21   0   0        0   6.0    6   42       0     61      2   NaN  5-11  191.0  4.37  38.0  15.0  122.0   NaN   NaN
102   3  103  LAR             Ernest Jones   LB   21   0   0        3  37.0   13   78       0    313      9   6.5   6-1  230.0  4.65  38.5   NaN    NaN   NaN   NaN
104   3  105  DEN           Baron Browning   LB   22   0   0        1  18.0   15   66       0     91      2  13.5   6-2  245.0  4.58  40.0  23.0  130.0  6.78  4.23
105   4  106  JAX               Jay Tufele   DL   22   0   0        0   5.0    0   46       0     21    NaN   0.5   6-2  305.0  5.00  30.0  30.0  105.0  7.80  4.88
110   4  111  CIN           Cameron Sample   DE   21   0   0        0   7.0    7   61       0     53    NaN     7   6-2  267.0  4.72  37.0  23.0  116.0  7.39  4.48
112   4  113  DET           Derrick Barnes   DE   22   0   0        2  17.0   17   68       0    159      1     8   NaN  238.0  4.57  37.0  29.0  119.0   NaN  4.27
114   4  115  DAL               Jabril Cox   LB   23   0   0        0   3.0    2   26       0      7    NaN   NaN   6-3  232.0   NaN   NaN   NaN    NaN   NaN   NaN
115   4  116  NYG            Elerson Smith   DL   23   0   0        0   1.0    1   15       0      4    NaN   NaN   NaN    NaN  4.71  41.5  26.0  127.0  7.00  4.39
116   4  117  LAR              Bobby Brown   DL   21   0   0        2  16.0   13   66       0     50    NaN     1   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
117   4  118  LAC              Chris Rumph   DE   22   0   0        0   4.0    3   54       0     43    NaN     5   6-2  244.0   NaN   NaN  18.0    NaN   NaN   NaN
120   4  121  JAX             Jordan Smith  OLB   23   0   0        0   0.0    0    2       0      1    NaN   NaN   6-5  264.0  4.80  33.0  16.0  117.0   NaN   NaN
121   4  122  CIN            Tyler Shelvin   DT   23   0   0        0   0.0    0    5       0      1    NaN   NaN   6-2  350.0  5.40  28.5   NaN   97.0  8.15  5.05
122   4  123  PHI          Zech McPhearson   DB   23   0   0        0   2.0    2   33       0     19    NaN     1  5-10  191.0  4.48  40.5  14.0  130.0  6.88  4.00
129   4  130  LAR           Robert Rochell   DB   23   0   0        0   4.0    3   54       0     24      1   NaN  5-11  193.0  4.41  43.0   9.0  133.0  6.84  4.08
131   4  132  CLE             Tommy Togiai   DT   21   0   0        0   7.0    2   41       0     50    NaN     4   6-1  296.0  4.97  32.0  40.0  105.0  7.20  4.49
133   4  134  MIN        Janarius Robinson   DE   22   0   0        0   2.0  NaN   16       0      7    NaN   1.5   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
134   4  135  TEN            Rashad Weaver   DL   23   0   0        0   5.0    5   36       0     29    NaN   5.5   6-4  259.0  4.88  32.0  20.0  114.0  6.97  4.26
139   4  140  PIT            Buddy Johnson   LB   22   0   0        0   2.0    0   33       0     16    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
142   4  143  LVR          Tyree Gillespie    S   23   0   0        0   1.0    1   14       0      1    NaN   NaN   NaN    NaN  4.38   NaN  15.0    NaN  7.06   NaN
143   4  144  KAN           Joshua Kaindoh   DE   22   0   0        0   0.0    0    3       0    NaN    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
145   5  146  NYJ          Jamien Sherwood   DB   21   0   0        2  16.0   16   73       0    217    NaN   4.5   6-1  216.0  4.76  36.0  15.0  123.0  7.15  4.36
147   5  148  ATL           Ta'Quon Graham   DL   22   0   0        1   9.0    9   51       0     38    NaN     1   6-3  292.0  4.89  32.5  32.0  113.0  7.31  4.68
151   5  152  DEN             Caden Sterns   DB   21   0   0        0   3.0    3   21       0     36      4     2  5-11  202.0  4.41  42.0  14.0  128.0  6.96  4.13
152   5  153  CLE              Tony Fields   LB   22   0   0        0   9.0    9   45       0     48      1   NaN   NaN  222.0  4.64  34.0  17.0  114.0  7.15  4.48
153   5  154  NYJ        Michael Carter II    S   22   0   0        0  11.0   10   73       0    164      2     1   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
155   5  156  PIT       Isaiahh Loudermilk   DE   23   0   0        0   6.0    6   60       0     38    NaN     1   6-6  274.0  5.08  28.5  21.0  112.0  7.52  4.55
157   5  158  CAR            Daviyon Nixon   DT   22   0   0        0   1.0    1   14       0      4    NaN   0.5   6-3  313.0  4.90  28.5   NaN  106.0  7.68  4.70
162   5  163  WAS          Darrick Forrest    S   22   0   0        1   7.0    7   40       0     84      4   NaN  5-11  206.0  4.42  39.0  21.0  132.0  6.91  4.23
163   5  164  DEN            Jamar Johnson   DB   21   0   0        0   0.0    0    3       0    NaN    NaN   NaN   6-2  205.0  4.58  35.0  17.0  122.0  7.22  4.41
164   5  165  IND              Shawn Davis   DB   23   0   0        0   0.0  NaN    1       0    NaN    NaN   NaN  5-10  202.0   NaN  39.5  17.0  128.0   NaN   NaN
165   5  166  CAR             Keith Taylor   DB   22   0   0        0   5.0    4   47       0     62    NaN   NaN   6-2  187.0  4.54  33.5  12.0  127.0  6.85  4.26
168   5  169  CLE         Richard LeCounte   DB   22   0   0        0   1.0    1   12       0      2    NaN   NaN  5-10  196.0  4.79  32.5   NaN  128.0  7.44  4.49
169   5  170  HOU            Garret Wallow   LB   22   0   0        0   5.0    4   46       0     28    NaN     1   NaN    NaN  4.65  32.5  22.0  122.0  6.87  4.12
170   5  171  BAL             Daelin Hayes   DL   23   0   0        0   0.0    0    1       0    NaN    NaN   NaN   6-3  253.0  4.71  32.5  26.0  119.0  7.17  4.29
172   5  173  GNB         Tedarrell Slaton   DL   23   0   0        3  23.0   17   85       0     86    NaN     5   6-4  330.0  5.09  29.0  27.0  109.0  7.91  4.81
173   5  174  LAR         Earnest Brown IV   DE   22   0   0        0   1.0    1   15       0      5    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
175   5  176  TAM               K.J. Britt   LB   22   0   0        1  10.0   10   76       0     80    NaN   0.5   NaN  235.0  4.76  32.5  24.0  118.0  7.38  4.40
176   5  177  NWE          Cameron McGrone   LB   21   0   0        0   2.0  NaN   27       0      8    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
177   5  178  GNB      Shemar Jean-Charles   DB   23   0   0        0   2.0    1   37       0     16      1   NaN  5-10  184.0  4.47  35.0  19.0  124.0  7.19  4.27
179   5  180  SFO          Talanoa Hufanga    S   22   1   1        3  29.0   19   66       0    216      7     4   NaN    NaN  4.65   NaN   NaN    NaN   NaN   NaN
181   5  182  ATL      Adetokunbo Ogundeji   DL   22   0   0        2  10.0   10   35       0     37    NaN     3   6-4  260.0  4.75  32.0  22.0  120.0  7.17  4.64
184   6  185  LAC             Nick Niemann   LB   23   0   0        0   5.0    5   71       0     54      1   NaN   6-3  234.0  4.45  33.5   NaN  121.0  6.67  4.14
185   6  186  NYJ       Hamsah Nasirildeen   DB   22   0   0        0   2.0    2   19       0      5    NaN   NaN   6-3  215.0   NaN  32.0  17.0    NaN  7.05  4.31
187   6  188  NWE          Joshuah Bledsoe    S   22   0   0        0   0.0    0    4       0    NaN    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
188   6  189  PHI         Marlon Tuipulotu   DL   22   0   0        0   2.0    2   33       0     24    NaN     3   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
190   6  191  PHI           Tarron Jackson   DE   23   0   0        0   1.0    1   24       0     11    NaN     1   6-2  254.0  4.68  29.0  25.0  118.0  7.45  4.51
191   6  192  DAL          Quinton Bohanna   DT   22   0   0        1   8.0    6   40       0     16    NaN   NaN   6-4  327.0  5.46  29.0   NaN   99.0  8.21  5.15
194   6  195  HOU                Roy Lopez   DL   24   0   0        3  22.0   12   80       0     83    NaN     5   6-1  304.0  5.19  31.0  36.0  105.0  7.39  4.51
198   6  199  MIN            Jaylen Twyman   DL   22   0   0        0   NaN  NaN  NaN     NaN    NaN    NaN   NaN   6-1  301.0  5.40  32.5  40.0  104.0  8.00   NaN
206   6  207  NYJ        Jonathan Marshall   DL   23   0   0        0   0.0    0    4       0      1    NaN   NaN   6-3  310.0  4.88  32.0  36.0  114.0   NaN   NaN
209   6  210  ARI          Victor Dimukeje   DE   21   0   0        0   6.0    6   60       0     43    NaN     4   6-1  262.0  4.87  34.5  28.0  115.0  7.25  4.35
211   6  212  BUF             Damar Hamlin   DB   23   0   0        2  11.0   11   53       0    130      2   1.5   NaN  200.0  4.60  35.0  18.0  118.0  6.93  4.40
214   6  215  TEN             Brady Breeze    S   23   0   0        0   0.0    0   11       0      5    NaN   NaN  5-11  197.0  4.55  38.0  20.0  120.0  7.05  4.22
215   6  216  PIT             Quincy Roche   DL   23   0   0        0   2.0  NaN   17       0     23    NaN   2.5   NaN    NaN   NaN  32.5  23.0  119.0   NaN   NaN
219   6  220  GNB          Isaiah McDuffie   LB   22   0   0        2  19.0   19   80       0    176      1     2   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
222   6  223  ARI                Tay Gowan   DB   23   0   0        0   0.0  NaN    6       0      1    NaN   NaN   NaN  186.0  4.44  35.5  13.0  118.0  6.88  4.25
223   6  224  PHI           JaCoby Stevens    S   23   0   0        0   0.0    0    2       0      1    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
226   6  227  DAL           Israel Mukuamu   DB   21   0   0        0   4.0    4   51       0     29      3   NaN   NaN    NaN   NaN  36.0  34.0    NaN   NaN   NaN
231   7  232  CAR             Phil Hoskins   DT   24   0   0        0   1.0    0   13       0      6    NaN     1   6-4  313.0  5.23  30.5  20.0  103.0  7.87  4.85
233   7  234  PHI          Patrick Johnson   DE   23   0   0        0   6.0    5   70       0     29    NaN     1   6-6  240.0  4.59  35.0  16.0  119.0  6.97  4.41
234   7  235  CIN             Wyatt Hubert   DE   23   0   0        0   NaN  NaN  NaN     NaN    NaN    NaN   NaN   6-2  258.0  4.93  32.5   NaN  110.0  7.03  4.28
238   7  239  DEN          Jonathon Cooper   DE   23   0   0        4  32.0   32   81       0    145      1  31.5   6-2  253.0  4.69  33.0  28.0  108.0  6.99  4.31
239   7  240  WAS     William Bradley-King  OLB   23   0   0        0   0.0    0    4       0      1    NaN   0.5   6-3  252.0  4.74  34.5   NaN  119.0  7.14  4.26
240   7  241  LAC                Mark Webb   DB   22   0   0        0   0.0    0    7       0      3    NaN   NaN   6-1  207.0  4.61  36.5   NaN  136.0  7.30  4.52
242   7  243  ARI            James Wiggins    S   24   0   0        0   0.0    0    3       0    NaN    NaN   NaN  5-11  209.0  4.40  38.0  22.0  127.0   NaN   NaN
244   7  245  PIT              Tre Norwood   DB   22   0   0        0   3.0    3   32       0     49      1   NaN  5-11  192.0  4.58  33.5  12.0  123.0  7.65  4.45
245   7  246  WAS              Shaka Toney   DE   23   0   0        0   2.0    2   26       0      6    NaN   1.5   6-2  242.0  4.51  39.0  24.0  128.0  6.95  4.28
249   7  250  CHI            Khyiris Tonga   DL   25   0   0        0   9.0    2   67       0     46    NaN   0.5   NaN    NaN   NaN   NaN  35.0    NaN   NaN   NaN
250   7  251  TAM             Chris Wilcox   DB   23   0   0        0   NaN  NaN  NaN     NaN    NaN    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
251   7  252  LAR            Chris Garrett   DE   23   0   0        0   0.0    0    1       0    NaN    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
252   7  253  DEN         Marquiss Spencer   DE   24   0   0        0   0.0    0    1       0    NaN    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
258   7  259  TAM             Grant Stuard   LB   22   0   0        0   7.0    1   83       0     54    NaN   NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN
259   1    1  JAX            Travon Walker   DE   21   0   0        4  26.0   26   63       0    101      1  27.5   6-5  272.0  4.51  35.5   NaN  123.0  6.89  4.32
260   1    2  DET         Aidan Hutchinson   DE   22   0   2        3  31.0   31   56       0    118      5    43   6-7  260.0  4.74  36.0   NaN  117.0  6.73  4.15
263   1    5  NYG        Kayvon Thibodeaux   DE   21   0   0        3  24.0   24   53       0     86    NaN  23.5   6-4  254.0  4.58   NaN  27.0    NaN   NaN   NaN

In [77]:
import matplotlib.pyplot as plt
import seaborn as sns

# # Boxplot of Best Performing Defensive Positions
# sns.boxplot(data = defenseAll, x = "Pos", y = "PlAV")
# plt.show()