In [61]:
#Imports 
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
import sklearn
from sklearn.linear_model import Perceptron
from sklearn import metrics
from sklearn.linear_model import LinearRegression

In [2]:
Combine_Data = pd.read_csv("2021Combine.csv")
Combine_Data.head()

,Name,Pos,School,Height,Weight,Hands,Arms,Wingspan,40 Yd,10 Split,Vertical,Broad,Bench,3-Cone,Shuttle
0,Adam Krumholz,WR,Wisconsin,"6'0""",193.0,NaN,NaN,NaN,4.60,NaN,35.5,"9'10""",11.0,7.03,4.28
1,Adrian Hardy,WR,Louisiana Tech,"6'1""",205.0,NaN,NaN,NaN,4.61,NaN,37.5,"10'4""",12.0,6.96,4.50
2,Amari Rodgers,WR,Clemson,"5'9""",212.0,NaN,NaN,NaN,4.52,NaN,33.0,"10'1""",19.0,7.07,4.31
3,Amon-Ra St. Brown,WR,USC,"5'11""",197.0,NaN,NaN,NaN,4.51,NaN,38.5,"10'7""",20.0,6.88,4.17
4,Anthony Schwartz,WR,Auburn,"6'0""",186.0,NaN,NaN,NaN,4.27,NaN,32.0,"10'3""",NaN,7.13,4.25

In [65]:
Combine_df = pd.DataFrame(Combine_Data)
Combine_df = Combine_df.drop(['Hands', 'Arms', 'Wingspan', '10 Split'], axis = 1)
Combine_df.head()

,Name,Pos,School,Height,Weight,40 Yd,Vertical,Broad,Bench,3-Cone,Shuttle
0,Adam Krumholz,WR,Wisconsin,"6'0""",193.0,4.60,35.5,"9'10""",11.0,7.03,4.28
1,Adrian Hardy,WR,Louisiana Tech,"6'1""",205.0,4.61,37.5,"10'4""",12.0,6.96,4.50
2,Amari Rodgers,WR,Clemson,"5'9""",212.0,4.52,33.0,"10'1""",19.0,7.07,4.31
3,Amon-Ra St. Brown,WR,USC,"5'11""",197.0,4.51,38.5,"10'7""",20.0,6.88,4.17
4,Anthony Schwartz,WR,Auburn,"6'0""",186.0,4.27,32.0,"10'3""",NaN,7.13,4.25

In [4]:
WR_df = Combine_df.loc[Combine_df['Pos'] == 'WR']
WR_df.head()

,Name,Pos,School,Height,Weight,40 Yd,Vertical,Broad,Bench,3-Cone,Shuttle
0,Adam Krumholz,WR,Wisconsin,"6'0""",193.0,4.60,35.5,"9'10""",11.0,7.03,4.28
1,Adrian Hardy,WR,Louisiana Tech,"6'1""",205.0,4.61,37.5,"10'4""",12.0,6.96,4.50
2,Amari Rodgers,WR,Clemson,"5'9""",212.0,4.52,33.0,"10'1""",19.0,7.07,4.31
3,Amon-Ra St. Brown,WR,USC,"5'11""",197.0,4.51,38.5,"10'7""",20.0,6.88,4.17
4,Anthony Schwartz,WR,Auburn,"6'0""",186.0,4.27,32.0,"10'3""",NaN,7.13,4.25

In [66]:
WR_df = WR_df.fillna(0)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

print(WR_df)

                         Name Pos           School Height  Weight  40 Yd  \
0               Adam Krumholz  WR        Wisconsin   6'0"   193.0   4.60
1                Adrian Hardy  WR   Louisiana Tech   6'1"   205.0   4.61
2               Amari Rodgers  WR          Clemson   5'9"   212.0   4.52
3           Amon-Ra St. Brown  WR              USC  5'11"   197.0   4.51
4            Anthony Schwartz  WR           Auburn   6'0"   186.0   4.27
5                Antonio Nunn  WR          Buffalo  5'11"   204.0   4.50
8              Bailey Gaither  WR     San Jose St.   6'0"   188.0   4.45
10              Ben Skowronek  WR       Notre Dame   6'2"   220.0   0.00
11               Blake Proehl  WR    East Carolina   6'1"   186.0   4.47
14               Branden Mack  WR           Temple   6'5"   217.0   4.66
15              Brandon Smith  WR             Iowa   6'1"   218.0   4.62
17             Brennan Eagles  WR            Texas   6'3"   225.0   4.55
27           Connor Wedington  WR         Stanford   6'0"   196.0   4.47
29             Cornell Powell  WR          Clemson   6'0"   204.0   4.53
30           D'Wayne Eskridge  WR   West. Michigan   5'8"   190.0   4.38
31             Damon Hazelton  WR         Missouri      0     0.0   4.60
32              Damonte Coxie  WR          Memphis   6'2"   198.0   4.77
36                  Dax Milne  WR              BYU      0     0.0   4.54
37               Dazz Newsome  WR   North Carolina  5'10"   190.0   4.59
41            DeVontres Dukes  WR    South Florida   6'3"   216.0   4.81
42            Dez Fitzpatrick  WR       Louisville   6'1"   208.0   4.43
43              Dillon Stoner  WR     Oklahoma St.   6'0"   194.0   4.51
44                Dyami Brown  WR   North Carolina   6'0"   189.0   4.46
45                  Eli Stove  WR           Auburn  5'11"   194.0   4.54
47               Elijah Moore  WR      Mississippi      0     0.0   4.35
49                Frank Darby  WR      Arizona St.   6'0"   201.0   4.56
58       Ihmir Smith-Marsette  WR             Iowa   6'0"   181.0   4.43
59               Isaiah McKoy  WR         Kent St.   6'2"   200.0   4.68
62              Ja'Marr Chase  WR              LSU   6'0"   201.0   4.34
64               Jacob Harris  WR  Central Florida   6'5"   219.0   4.39
65              Jaelon Darden  WR      North Texas   5'7"   174.0   4.47
68                 Jalen Camp  WR     Georgia Tech   6'1"   226.0   4.48
74              Jaylen Harris  WR         Ohio St.   5'8"   170.0   4.77
78          Johnathon Johnson  WR         Missouri      0     0.0   0.00
79             Jonathan Adams  WR     Arkansas St.   6'2"   210.0   4.59
80             Jonathan Nance  WR         Missouri      0     0.0   0.00
81              Josh Blancato  WR     Georgia Tech   5'9"   182.0   4.55
82          Josh Imatorbhebhe  WR         Illinois   6'0"   218.0   4.53
87             Kadarius Toney  WR          Florida  5'11"   193.0   4.39
88               Kawaan Baker  WR    South Alabama   6'0"   210.0   4.44
93             Khalil McClain  WR             Troy   6'2"   214.0   4.70
100           Marlon Williams  WR  Central Florida  5'11"   209.0   4.63
101         Marquez Stevenson  WR          Houston  5'10"   180.0   4.48
105              Nico Collins  WR         Michigan   6'4"   215.0   4.43
113              Racey McMath  WR              LSU   6'2"   217.0   4.36
115  Ramaud Chiaokhiao-Bowman  WR     Northwestern   6'1"   204.0   4.78
116            Rashod Bateman  WR        Minnesota   6'0"   190.0   4.39
118                Riley Lees  WR     Northwestern  5'11"   192.0   4.47
119             Rondale Moore  WR           Purdue   5'7"   180.0   4.28
120              Sage Surratt  WR      Wake Forest   6'2"   209.0   4.66
124             Seth Williams  WR           Auburn   6'3"   211.0   4.49
126               Simi Fehoko  WR         Stanford   6'3"   222.0   4.44
128           Tamorrion Terry  WR      Florida St.   6'2"   207.0   4.44
129               Tarik Black  WR            Texas   6'2"   213.0   4.54
130      Terrace Marshall Jr.  WR              LSU   6'2"   205.0   4.40
133                 Tre Nixon  WR  Central Florida   6'0"   187.0   4.44
134                Tre Walker  WR     San Jose St.  5'10"   178.0   4.58
136             Trevon Grimes  WR          Florida   6'4"   220.0   4.49
141               Tutu Atwell  WR       Louisville   5'8"   155.0   4.42
142             Tylan Wallace  WR     Oklahoma St.  5'11"   194.0   4.48
143             Tyler Vaughns  WR              USC   6'1"   190.0   4.62
144            Warren Jackson  WR     Colorado St.   6'6"   219.0   4.68
145              Whop Philyor  WR          Indiana   5'9"   184.0   4.57

     Vertical   Broad  Bench  3-Cone  Shuttle   PFF  PFF_label  PFF_binary  \
0        35.5   9'10"   11.0    7.03     4.28   0.0          0           0
1        37.5   10'4"   12.0    6.96     4.50   0.0          0           0
2        33.0   10'1"   19.0    7.07     4.31  58.0          0           0
3        38.5   10'7"   20.0    6.88     4.17  91.0          3           1
4        32.0   10'3"    0.0    7.13     4.25  56.0          0           0
5        33.5   10'0"   15.0    7.12     4.32   0.0          0           0
8        31.0   10'1"    9.0    7.07     4.39   0.0          0           0
10        0.0       0   13.0    0.00     0.00  62.0          1           1
11       36.0   10'6"   12.0    7.00     4.06   0.0          0           0
14       31.0    9'7"   11.0    7.13     4.37   0.0          0           0
15       39.5  10'10"    0.0    0.00     0.00   0.0          0           0
17       36.5   10'5"    0.0    6.93     4.42   0.0          0           0
27       38.5    9'9"   13.0    6.66     4.07   0.0          0           0
29       36.5   10'8"   16.0    7.03     4.21  57.0          0           0
30       35.0   10'4"    0.0    6.93     4.22  60.0          1           1
31       37.5       0    0.0    0.00     0.00   0.0          0           0
32       30.5   10'2"    4.0    6.92     4.45   0.0          0           0
36       31.0    9'6"   14.0    0.00     4.19  64.0          1           1
37       34.0   10'1"   12.0    7.38     4.38  60.0          1           1
41       33.0   10'2"   16.0    7.07     4.41   0.0          0           0
42       35.0       0    0.0    7.09     4.26  59.0          0           0
43       37.0   10'3"   16.0    6.96     4.13   0.0          0           0
44       35.0   10'8"   18.0    6.87     4.35  62.0          1           1
45       30.5   9'11"   14.0    7.34     4.40   0.0          0           0
47       36.0   10'1"   17.0    6.63     4.07  72.0          2           1
49       34.5    9'9"   19.0    7.05     4.25  58.0          0           0
58       37.0   10'4"    0.0    7.00     4.20  61.0          1           1
59       29.5    9'6"   12.0    7.09     4.36   0.0          0           0
62       41.0   11'0"    0.0    6.96     3.99  90.0          3           1
64       40.5   11'1"   15.0    6.54     4.31  60.0          1           1
65       35.5   10'2"    0.0    6.66     3.98  64.0          1           1
68       39.5   10'5"   29.0    7.00     4.14  58.0          0           0
74       30.5    9'1"    8.0    7.37     4.50   0.0          0           0
78        0.0       0    0.0    0.00     0.00   0.0          0           0
79       39.0   11'0"    0.0    7.04     4.38   0.0          0           0
80        0.0       0    0.0    0.00     0.00   0.0          0           0
81       32.0   10'4"   17.0    6.90     4.31   0.0          0           0
82       46.5   11'2"   24.0    7.10     4.38   0.0          0           0
87       39.5   11'4"    9.0    6.88     4.25  66.0          1           1
88       39.5   10'9"   21.0    7.42     4.41   0.0          0           0
93       32.0    9'6"   15.0    7.72     4.50   0.0          0           0
100      33.5   9'11"   14.0    0.00     4.57   0.0          0           0
101      33.0   10'2"    0.0    6.76     4.14  60.0          1           1
105      37.5   10'5"   14.0    6.78     4.29  78.0          2           1
113      34.0   10'4"    0.0    7.38     4.38  60.0          1           1
115      34.5   9'11"   11.0    6.78     4.20   0.0          0           0
116      36.0   10'3"    0.0    0.00     0.00  74.0          2           1
118      35.0   9'11"    7.0    6.78     4.16   0.0          0           0
119      42.5       0    0.0    6.65     4.06  78.0          2           1
120       0.0       0   18.0    0.00     4.25   0.0          0           0
124      37.0   10'4"   12.0    7.20     4.43   0.0          0           0
126      34.5   10'0"   16.0    6.78     4.26  55.0          0           0
128      32.5   10'6"   15.0    7.00     4.53   0.0          0           0
129      40.0   11'0"   15.0    6.91     4.26   0.0          0           0
130      39.0   10'5"   19.0    0.00     0.00  67.0          1           1
133      35.5   10'5"   18.0    6.81     4.27   0.0          0           0
134      28.0    9'5"    0.0    7.75     4.47   0.0          0           0
136      35.0   9'10"   15.0    6.98     4.28   0.0          0           0
141      33.0    9'9"    0.0    6.89     4.14  68.0          1           1
142      33.0    9'4"   11.0    6.97     4.25  62.0          1           1
143      31.5   10'0"    7.0    7.13     4.36   0.0          0           0
144      33.5   10'3"    0.0    7.81     4.53   0.0          0           0
145      31.0   10'0"   14.0    7.20     4.34   0.0          0           0

     FF_binary
0            0
1            0
2            0
3            1
4            0
5            0
8            0
10           1
11           0
14           0
15           0
17           0
27           0
29           0
30           1
31           0
32           0
36           1
37           1
41           0
42           0
43           0
44           1
45           0
47           1
49           0
58           1
59           0
62           1
64           1
65           1
68           0
74           0
78           0
79           0
80           0
81           0
82           0
87           1
88           0
93           0
100          0
101          1
105          1
113          1
115          0
116          1
118          0
119          1
120          0
124          0
126          0
128          0
129          0
130          1
133          0
134          0
136          0
141          1
142          1
143          0
144          0
145          0

In [67]:
pff_values = [
    # 1–15
    0.00, 0.00, 58.00, 91.00, 56.00,
    0.00, 0.00, 62.00, 0.00, 0.00,
    0.00, 0.00, 0.00, 57.00, 60.00,

    # 16–30
    0.00, 0.00, 64.00, 60.00, 0.00,
    59.00, 0.00, 62.00, 0.00, 72.00,
    58.00, 61.00, 0.00, 90.00, 60.00,

    # 31–45
    64.00, 58.00, 0.00, 0.00, 0.00,
    0.00, 0.00, 0.00, 66.00, 0.00,
    0.00, 0.00, 60.00, 78.00, 60.00,

    # 46–end
    0.00, 74.00, 0.00, 78.00, 0.00,
    0.00, 55.00, 0.00, 0.00, 67.00,
    0.00, 0.00, 0.00, 68.00, 62.00,
    0.00, 0.00, 0.00
]

WR_df["PFF"] = pff_values

print(WR_df[["PFF"]].head())
print(len(WR_df), len(pff_values))

    PFF
0   0.0
1   0.0
2  58.0
3  91.0
4  56.0
63 63

In [68]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

print(WR_df)

                         Name Pos           School Height  Weight  40 Yd  \
0               Adam Krumholz  WR        Wisconsin   6'0"   193.0   4.60
1                Adrian Hardy  WR   Louisiana Tech   6'1"   205.0   4.61
2               Amari Rodgers  WR          Clemson   5'9"   212.0   4.52
3           Amon-Ra St. Brown  WR              USC  5'11"   197.0   4.51
4            Anthony Schwartz  WR           Auburn   6'0"   186.0   4.27
5                Antonio Nunn  WR          Buffalo  5'11"   204.0   4.50
8              Bailey Gaither  WR     San Jose St.   6'0"   188.0   4.45
10              Ben Skowronek  WR       Notre Dame   6'2"   220.0   0.00
11               Blake Proehl  WR    East Carolina   6'1"   186.0   4.47
14               Branden Mack  WR           Temple   6'5"   217.0   4.66
15              Brandon Smith  WR             Iowa   6'1"   218.0   4.62
17             Brennan Eagles  WR            Texas   6'3"   225.0   4.55
27           Connor Wedington  WR         Stanford   6'0"   196.0   4.47
29             Cornell Powell  WR          Clemson   6'0"   204.0   4.53
30           D'Wayne Eskridge  WR   West. Michigan   5'8"   190.0   4.38
31             Damon Hazelton  WR         Missouri      0     0.0   4.60
32              Damonte Coxie  WR          Memphis   6'2"   198.0   4.77
36                  Dax Milne  WR              BYU      0     0.0   4.54
37               Dazz Newsome  WR   North Carolina  5'10"   190.0   4.59
41            DeVontres Dukes  WR    South Florida   6'3"   216.0   4.81
42            Dez Fitzpatrick  WR       Louisville   6'1"   208.0   4.43
43              Dillon Stoner  WR     Oklahoma St.   6'0"   194.0   4.51
44                Dyami Brown  WR   North Carolina   6'0"   189.0   4.46
45                  Eli Stove  WR           Auburn  5'11"   194.0   4.54
47               Elijah Moore  WR      Mississippi      0     0.0   4.35
49                Frank Darby  WR      Arizona St.   6'0"   201.0   4.56
58       Ihmir Smith-Marsette  WR             Iowa   6'0"   181.0   4.43
59               Isaiah McKoy  WR         Kent St.   6'2"   200.0   4.68
62              Ja'Marr Chase  WR              LSU   6'0"   201.0   4.34
64               Jacob Harris  WR  Central Florida   6'5"   219.0   4.39
65              Jaelon Darden  WR      North Texas   5'7"   174.0   4.47
68                 Jalen Camp  WR     Georgia Tech   6'1"   226.0   4.48
74              Jaylen Harris  WR         Ohio St.   5'8"   170.0   4.77
78          Johnathon Johnson  WR         Missouri      0     0.0   0.00
79             Jonathan Adams  WR     Arkansas St.   6'2"   210.0   4.59
80             Jonathan Nance  WR         Missouri      0     0.0   0.00
81              Josh Blancato  WR     Georgia Tech   5'9"   182.0   4.55
82          Josh Imatorbhebhe  WR         Illinois   6'0"   218.0   4.53
87             Kadarius Toney  WR          Florida  5'11"   193.0   4.39
88               Kawaan Baker  WR    South Alabama   6'0"   210.0   4.44
93             Khalil McClain  WR             Troy   6'2"   214.0   4.70
100           Marlon Williams  WR  Central Florida  5'11"   209.0   4.63
101         Marquez Stevenson  WR          Houston  5'10"   180.0   4.48
105              Nico Collins  WR         Michigan   6'4"   215.0   4.43
113              Racey McMath  WR              LSU   6'2"   217.0   4.36
115  Ramaud Chiaokhiao-Bowman  WR     Northwestern   6'1"   204.0   4.78
116            Rashod Bateman  WR        Minnesota   6'0"   190.0   4.39
118                Riley Lees  WR     Northwestern  5'11"   192.0   4.47
119             Rondale Moore  WR           Purdue   5'7"   180.0   4.28
120              Sage Surratt  WR      Wake Forest   6'2"   209.0   4.66
124             Seth Williams  WR           Auburn   6'3"   211.0   4.49
126               Simi Fehoko  WR         Stanford   6'3"   222.0   4.44
128           Tamorrion Terry  WR      Florida St.   6'2"   207.0   4.44
129               Tarik Black  WR            Texas   6'2"   213.0   4.54
130      Terrace Marshall Jr.  WR              LSU   6'2"   205.0   4.40
133                 Tre Nixon  WR  Central Florida   6'0"   187.0   4.44
134                Tre Walker  WR     San Jose St.  5'10"   178.0   4.58
136             Trevon Grimes  WR          Florida   6'4"   220.0   4.49
141               Tutu Atwell  WR       Louisville   5'8"   155.0   4.42
142             Tylan Wallace  WR     Oklahoma St.  5'11"   194.0   4.48
143             Tyler Vaughns  WR              USC   6'1"   190.0   4.62
144            Warren Jackson  WR     Colorado St.   6'6"   219.0   4.68
145              Whop Philyor  WR          Indiana   5'9"   184.0   4.57

     Vertical   Broad  Bench  3-Cone  Shuttle   PFF  PFF_label  PFF_binary  \
0        35.5   9'10"   11.0    7.03     4.28   0.0          0           0
1        37.5   10'4"   12.0    6.96     4.50   0.0          0           0
2        33.0   10'1"   19.0    7.07     4.31  58.0          0           0
3        38.5   10'7"   20.0    6.88     4.17  91.0          3           1
4        32.0   10'3"    0.0    7.13     4.25  56.0          0           0
5        33.5   10'0"   15.0    7.12     4.32   0.0          0           0
8        31.0   10'1"    9.0    7.07     4.39   0.0          0           0
10        0.0       0   13.0    0.00     0.00  62.0          1           1
11       36.0   10'6"   12.0    7.00     4.06   0.0          0           0
14       31.0    9'7"   11.0    7.13     4.37   0.0          0           0
15       39.5  10'10"    0.0    0.00     0.00   0.0          0           0
17       36.5   10'5"    0.0    6.93     4.42   0.0          0           0
27       38.5    9'9"   13.0    6.66     4.07   0.0          0           0
29       36.5   10'8"   16.0    7.03     4.21  57.0          0           0
30       35.0   10'4"    0.0    6.93     4.22  60.0          1           1
31       37.5       0    0.0    0.00     0.00   0.0          0           0
32       30.5   10'2"    4.0    6.92     4.45   0.0          0           0
36       31.0    9'6"   14.0    0.00     4.19  64.0          1           1
37       34.0   10'1"   12.0    7.38     4.38  60.0          1           1
41       33.0   10'2"   16.0    7.07     4.41   0.0          0           0
42       35.0       0    0.0    7.09     4.26  59.0          0           0
43       37.0   10'3"   16.0    6.96     4.13   0.0          0           0
44       35.0   10'8"   18.0    6.87     4.35  62.0          1           1
45       30.5   9'11"   14.0    7.34     4.40   0.0          0           0
47       36.0   10'1"   17.0    6.63     4.07  72.0          2           1
49       34.5    9'9"   19.0    7.05     4.25  58.0          0           0
58       37.0   10'4"    0.0    7.00     4.20  61.0          1           1
59       29.5    9'6"   12.0    7.09     4.36   0.0          0           0
62       41.0   11'0"    0.0    6.96     3.99  90.0          3           1
64       40.5   11'1"   15.0    6.54     4.31  60.0          1           1
65       35.5   10'2"    0.0    6.66     3.98  64.0          1           1
68       39.5   10'5"   29.0    7.00     4.14  58.0          0           0
74       30.5    9'1"    8.0    7.37     4.50   0.0          0           0
78        0.0       0    0.0    0.00     0.00   0.0          0           0
79       39.0   11'0"    0.0    7.04     4.38   0.0          0           0
80        0.0       0    0.0    0.00     0.00   0.0          0           0
81       32.0   10'4"   17.0    6.90     4.31   0.0          0           0
82       46.5   11'2"   24.0    7.10     4.38   0.0          0           0
87       39.5   11'4"    9.0    6.88     4.25  66.0          1           1
88       39.5   10'9"   21.0    7.42     4.41   0.0          0           0
93       32.0    9'6"   15.0    7.72     4.50   0.0          0           0
100      33.5   9'11"   14.0    0.00     4.57   0.0          0           0
101      33.0   10'2"    0.0    6.76     4.14  60.0          1           1
105      37.5   10'5"   14.0    6.78     4.29  78.0          2           1
113      34.0   10'4"    0.0    7.38     4.38  60.0          1           1
115      34.5   9'11"   11.0    6.78     4.20   0.0          0           0
116      36.0   10'3"    0.0    0.00     0.00  74.0          2           1
118      35.0   9'11"    7.0    6.78     4.16   0.0          0           0
119      42.5       0    0.0    6.65     4.06  78.0          2           1
120       0.0       0   18.0    0.00     4.25   0.0          0           0
124      37.0   10'4"   12.0    7.20     4.43   0.0          0           0
126      34.5   10'0"   16.0    6.78     4.26  55.0          0           0
128      32.5   10'6"   15.0    7.00     4.53   0.0          0           0
129      40.0   11'0"   15.0    6.91     4.26   0.0          0           0
130      39.0   10'5"   19.0    0.00     0.00  67.0          1           1
133      35.5   10'5"   18.0    6.81     4.27   0.0          0           0
134      28.0    9'5"    0.0    7.75     4.47   0.0          0           0
136      35.0   9'10"   15.0    6.98     4.28   0.0          0           0
141      33.0    9'9"    0.0    6.89     4.14  68.0          1           1
142      33.0    9'4"   11.0    6.97     4.25  62.0          1           1
143      31.5   10'0"    7.0    7.13     4.36   0.0          0           0
144      33.5   10'3"    0.0    7.81     4.53   0.0          0           0
145      31.0   10'0"   14.0    7.20     4.34   0.0          0           0

     FF_binary
0            0
1            0
2            0
3            1
4            0
5            0
8            0
10           1
11           0
14           0
15           0
17           0
27           0
29           0
30           1
31           0
32           0
36           1
37           1
41           0
42           0
43           0
44           1
45           0
47           1
49           0
58           1
59           0
62           1
64           1
65           1
68           0
74           0
78           0
79           0
80           0
81           0
82           0
87           1
88           0
93           0
100          0
101          1
105          1
113          1
115          0
116          1
118          0
119          1
120          0
124          0
126          0
128          0
129          0
130          1
133          0
134          0
136          0
141          1
142          1
143          0
144          0
145          0

In [70]:
PFF_labels = WR_df["PFF"]

features = WR_df.drop(['Name', 'Pos', 'School', 'Height','PFF', 'PFF_binary', 'Broad'], axis=1)

train_vectors, test_vectors, train_labels, test_labels = train_test_split(features, PFF_labels, test_size=0.25, random_state=42)

model = LinearRegression()
model.fit(train_vectors, train_labels)

preds = model.predict(test_vectors)

X = sm.add_constant(train_vectors)
model = sm.OLS(train_labels, X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    PFF   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.698
Method:                 Least Squares   F-statistic:                     14.31
Date:                Sun, 19 Apr 2026   Prob (F-statistic):           2.36e-09
Time:                        01:36:53   Log-Likelihood:                -198.82
No. Observations:                  47   AIC:                             415.6
Df Residuals:                      38   BIC:                             432.3
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.3847     11.617      0.205      0.838     -21.133      25.903
Weight         0.0324      0.053      0.617      0.541      -0.074       0.139
40 Yd         -2.5454      7.028     -0.362      0.719     -16.773      11.682
Vertical       0.2377      0.789      0.301      0.765      -1.359       1.834
Bench          0.1282      0.373      0.344      0.733      -0.627       0.883
3-Cone         0.6232      2.020      0.309      0.759      -3.466       4.712
Shuttle       -0.0013      3.965     -0.000      1.000      -8.027       8.024
PFF_label     12.9402      6.759      1.914      0.063      -0.744      26.624
FF_binary     39.8561     10.523      3.788      0.001      18.554      61.158
==============================================================================
Omnibus:                       28.587   Durbin-Watson:                   1.960
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.411
Skew:                           1.988   Prob(JB):                     5.07e-11
Kurtosis:                       5.898   Cond. No.                         895.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [74]:
from sklearn.metrics import r2_score, mean_absolute_error

print(r2_score(test_labels, preds))
print(mean_absolute_error(test_labels,preds))

0.46414498408570737
14.031415478140161